/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.gui;

import br.com.bd.Conexao;
import br.com.bd.UsuarioBD;
import br.com.controller.FormCadastroController;
import br.com.source.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Matheus Barbosa
 */
public class CadastroUsuarios extends javax.swing.JFrame {

    private final FormCadastroController controller;

    /**
     * Creates new form CadastroUsuarios
     */
    public CadastroUsuarios() {
        initComponents();
        controller = new FormCadastroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlInstrucao = new javax.swing.JLabel();
        jlPermissoesUsuario = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlNomeCompleto = new javax.swing.JLabel();
        jtfNomeCompleto = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfID = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jcbGestorUsuarios = new javax.swing.JCheckBox();
        jcbGestorQuadras = new javax.swing.JCheckBox();
        jcbZelador = new javax.swing.JCheckBox();
        jcbAnalistaRelatorios = new javax.swing.JCheckBox();
        jbCancelar = new javax.swing.JButton();
        jbAdicionarUsuario = new javax.swing.JButton();
        jlFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setText("Cadastro de usuários");
        getContentPane().add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jlInstrucao.setText("Preencha todos os campos e salve para adicionar um novo usuário.");
        getContentPane().add(jlInstrucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jlPermissoesUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/Permissões.png"))); // NOI18N
        jlPermissoesUsuario.setText("Permissões do usuário: ");
        getContentPane().add(jlPermissoesUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jlID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/ID.png"))); // NOI18N
        jlID.setText("ID do usuário:");
        getContentPane().add(jlID, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        jlEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/E-mail.png"))); // NOI18N
        jlEmail.setText("E-mail:");
        getContentPane().add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jlSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/Senha.png"))); // NOI18N
        jlSenha.setText("Senha: ");
        getContentPane().add(jlSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        jlNomeCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/Nome.png"))); // NOI18N
        jlNomeCompleto.setText("Nome completo:");
        getContentPane().add(jlNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));
        getContentPane().add(jtfNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 250, -1));
        getContentPane().add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 250, -1));

        jtfID.setEditable(false);
        getContentPane().add(jtfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 130, -1));

        jpfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jpfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 130, -1));

        jcbGestorUsuarios.setText("Gestor de usuários");
        getContentPane().add(jcbGestorUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jcbGestorQuadras.setText("Gestor de quadras");
        getContentPane().add(jcbGestorQuadras, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jcbZelador.setText("Zelador");
        jcbZelador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbZeladorActionPerformed(evt);
            }
        });
        getContentPane().add(jcbZelador, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jcbAnalistaRelatorios.setText("Analista de relatórios");
        getContentPane().add(jcbAnalistaRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/Sair.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        jbAdicionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/Adicionar usuário.png"))); // NOI18N
        jbAdicionarUsuario.setText("Adicionar usuário");
        jbAdicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jbAdicionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jlFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/fundo2.jpg"))); // NOI18N
        getContentPane().add(jlFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfSenhaActionPerformed

    private void jcbZeladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbZeladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbZeladorActionPerformed

    private void jbAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarUsuarioActionPerformed
        controller.salvarUsuario();
    }//GEN-LAST:event_jbAdicionarUsuarioActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        controller.cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuarios().setVisible(true);
            }
        });
    }

    public JCheckBox getJcbAnalistaRelatorios() {
        return jcbAnalistaRelatorios;
    }

    public void setJcbAnalistaRelatorios(JCheckBox jcbAnalistaRelatorios) {
        this.jcbAnalistaRelatorios = jcbAnalistaRelatorios;
    }

    public JCheckBox getJcbGestorQuadras() {
        return jcbGestorQuadras;
    }

    public void setJcbGestorQuadras(JCheckBox jcbGestorQuadras) {
        this.jcbGestorQuadras = jcbGestorQuadras;
    }

    public JCheckBox getJcbGestorUsuarios() {
        return jcbGestorUsuarios;
    }

    public void setJcbGestorUsuarios(JCheckBox jcbGestorUsuarios) {
        this.jcbGestorUsuarios = jcbGestorUsuarios;
    }

    public JCheckBox getJcbZelador() {
        return jcbZelador;
    }

    public void setJcbZelador(JCheckBox jcbZelador) {
        this.jcbZelador = jcbZelador;
    }

    public JPasswordField getJpfSenha() {
        return jpfSenha;
    }

    public void setJpfSenha(JPasswordField jpfSenha) {
        this.jpfSenha = jpfSenha;
    }

    public JTextField getJtfEmail() {
        return jtfEmail;
    }

    public void setJtfEmail(JTextField jtfEmail) {
        this.jtfEmail = jtfEmail;
    }

    public JTextField getJtfID() {
        return jtfID;
    }

    public void setJtfID(JTextField jtfID) {
        this.jtfID = jtfID;
    }

    public JTextField getJtfNomeCompleto() {
        return jtfNomeCompleto;
    }

    public void setJtfNomeCompleto(JTextField jtfNomeCompleto) {
        this.jtfNomeCompleto = jtfNomeCompleto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAdicionarUsuario;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JCheckBox jcbAnalistaRelatorios;
    private javax.swing.JCheckBox jcbGestorQuadras;
    private javax.swing.JCheckBox jcbGestorUsuarios;
    private javax.swing.JCheckBox jcbZelador;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlFundo;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlInstrucao;
    private javax.swing.JLabel jlNomeCompleto;
    private javax.swing.JLabel jlPermissoesUsuario;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfNomeCompleto;
    // End of variables declaration//GEN-END:variables
}
