/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.gui;

import br.com.controller.TelaPrincipalController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Matheus Barbosa
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private final TelaPrincipalController controller;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        controller = new TelaPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlFotoUsuario = new javax.swing.JLabel();
        jlNomeLogado = new javax.swing.JLabel();
        jlPermissoes = new javax.swing.JLabel();
        jlListaPermissoes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jlData = new javax.swing.JLabel();
        jlHora = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jmbGeral = new javax.swing.JMenuBar();
        jmAluguel = new javax.swing.JMenu();
        jmiNovaReserva = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmiConsultarReservas = new javax.swing.JMenuItem();
        jmQuadras = new javax.swing.JMenu();
        jmiNovaQuadra = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiConsultarQuadras = new javax.swing.JMenuItem();
        jmUsuarios = new javax.swing.JMenu();
        jmiNovoUsuario = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmiConsultarUsuarios = new javax.swing.JMenuItem();
        jmManutencoes = new javax.swing.JMenu();
        jmiNovaManutencao = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jmiConsultarManutencoes = new javax.swing.JMenuItem();
        jmRelatorios = new javax.swing.JMenu();
        jmiGanhoPorQuadra = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jmiGanhoPorPeriodo = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jmiOcupacaoPorQuadra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(325, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlFotoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/Conta de Usuário.png"))); // NOI18N
        jlFotoUsuario.setRequestFocusEnabled(false);
        jPanel1.add(jlFotoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 14, 131, 130));

        jlNomeLogado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlNomeLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNomeLogado.setText("jlNomeLogado");
        jPanel1.add(jlNomeLogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 151, 215, -1));

        jlPermissoes.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlPermissoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPermissoes.setText("Nível de permissões:");
        jPanel1.add(jlPermissoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 178, 215, -1));

        jlListaPermissoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlListaPermissoes.setText("jlListaPermissoes");
        jPanel1.add(jlListaPermissoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 207, 215, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 240, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 240, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 240, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 240, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 240, 10));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 240, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 240, 10));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlData.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jlData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/Consultar agenda.png"))); // NOI18N
        jlData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jlData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jlHora.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jlHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/clock.png"))); // NOI18N
        jlHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jlHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 220, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/logout.png"))); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 30, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 690));

        jmAluguel.setBorder(null);
        jmAluguel.setText("Aluguel");

        jmiNovaReserva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiNovaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/tennis.png"))); // NOI18N
        jmiNovaReserva.setText("Nova reserva...");
        jmAluguel.add(jmiNovaReserva);
        jmAluguel.add(jSeparator5);

        jmiConsultarReservas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiConsultarReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/Consultar agenda.png"))); // NOI18N
        jmiConsultarReservas.setText("Consultar reservas");
        jmAluguel.add(jmiConsultarReservas);

        jmbGeral.add(jmAluguel);

        jmQuadras.setBorder(null);
        jmQuadras.setText("Quadras");

        jmiNovaQuadra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/registro.png"))); // NOI18N
        jmiNovaQuadra.setText("Nova quadra");
        jmQuadras.add(jmiNovaQuadra);
        jmQuadras.add(jSeparator4);

        jmiConsultarQuadras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/court.png"))); // NOI18N
        jmiConsultarQuadras.setText("Consultar quadras");
        jmQuadras.add(jmiConsultarQuadras);

        jmbGeral.add(jmQuadras);

        jmUsuarios.setBorder(null);
        jmUsuarios.setText("Usuários");

        jmiNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/add-user.png"))); // NOI18N
        jmiNovoUsuario.setText("Novo usuário...");
        jmiNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovoUsuarioActionPerformed(evt);
            }
        });
        jmUsuarios.add(jmiNovoUsuario);
        jmUsuarios.add(jSeparator6);

        jmiConsultarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/search.png"))); // NOI18N
        jmiConsultarUsuarios.setText("Consultar usuários");
        jmiConsultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarUsuariosActionPerformed(evt);
            }
        });
        jmUsuarios.add(jmiConsultarUsuarios);

        jmbGeral.add(jmUsuarios);

        jmManutencoes.setBorder(null);
        jmManutencoes.setText("Manutenções");

        jmiNovaManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/add.png"))); // NOI18N
        jmiNovaManutencao.setText("Nova manutenção...");
        jmManutencoes.add(jmiNovaManutencao);
        jmManutencoes.add(jSeparator11);

        jmiConsultarManutencoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/manutencao.png"))); // NOI18N
        jmiConsultarManutencoes.setText("Consultar manutenções");
        jmiConsultarManutencoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarManutencoesActionPerformed(evt);
            }
        });
        jmManutencoes.add(jmiConsultarManutencoes);

        jmbGeral.add(jmManutencoes);

        jmRelatorios.setBorder(null);
        jmRelatorios.setText("Relatórios");

        jmiGanhoPorQuadra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/ganhos.png"))); // NOI18N
        jmiGanhoPorQuadra.setText("Ganho médio por quadra");
        jmRelatorios.add(jmiGanhoPorQuadra);
        jmRelatorios.add(jSeparator13);

        jmiGanhoPorPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/ganhos.png"))); // NOI18N
        jmiGanhoPorPeriodo.setText("Ganho total por período");
        jmRelatorios.add(jmiGanhoPorPeriodo);
        jmRelatorios.add(jSeparator14);

        jmiOcupacaoPorQuadra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gui/imagens/icones/Consulta por periodo.png"))); // NOI18N
        jmiOcupacaoPorQuadra.setText("Ocupação média por quadra");
        jmRelatorios.add(jmiOcupacaoPorQuadra);

        jmbGeral.add(jmRelatorios);

        setJMenuBar(jmbGeral);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiConsultarManutencoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarManutencoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiConsultarManutencoesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
        Login telaLogin = new Login();
        telaLogin.setVisible(false);
        
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jlData.setText(formato.format(dataSistema));
        
        Timer timer = new Timer (1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jmiNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovoUsuarioActionPerformed
        controller.cadastrarUsuario();
    }//GEN-LAST:event_jmiNovoUsuarioActionPerformed

    private void jmiConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarUsuariosActionPerformed
        controller.consultaUsuarios();
    }//GEN-LAST:event_jmiConsultarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlFotoUsuario;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel jlListaPermissoes;
    private javax.swing.JLabel jlNomeLogado;
    private javax.swing.JLabel jlPermissoes;
    private javax.swing.JMenu jmAluguel;
    private javax.swing.JMenu jmManutencoes;
    private javax.swing.JMenu jmQuadras;
    private javax.swing.JMenu jmRelatorios;
    private javax.swing.JMenu jmUsuarios;
    private javax.swing.JMenuBar jmbGeral;
    private javax.swing.JMenuItem jmiConsultarManutencoes;
    private javax.swing.JMenuItem jmiConsultarQuadras;
    private javax.swing.JMenuItem jmiConsultarReservas;
    private javax.swing.JMenuItem jmiConsultarUsuarios;
    private javax.swing.JMenuItem jmiGanhoPorPeriodo;
    private javax.swing.JMenuItem jmiGanhoPorQuadra;
    private javax.swing.JMenuItem jmiNovaManutencao;
    private javax.swing.JMenuItem jmiNovaQuadra;
    private javax.swing.JMenuItem jmiNovaReserva;
    private javax.swing.JMenuItem jmiNovoUsuario;
    private javax.swing.JMenuItem jmiOcupacaoPorQuadra;
    // End of variables declaration//GEN-END:variables
    class hora implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            Calendar agora = Calendar.getInstance();
            jlHora.setText(String.format("%1$tH:%1tM:%1$tS", agora));
        }
    }

}
