/**
 * Interface da tela de cadastro de usuários.
 * Permitindo que seja adicionar, editar, bloquear/desbloquear, habilitar/desabilitar e excluir um usuário.
 * @author Matheus Barbosa, Vinicius Sugawara.
 */
package br.com.VIEW;

import br.com.DAO.ConexaoDAO;
import br.com.DAO.UsuarioDAO;
import br.com.Controller.CadastroUsuarioController;
import br.com.DTO.UsuarioDTO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class CadastroUsuariosVIEW extends javax.swing.JFrame {

    private final CadastroUsuarioController controller;

    /**
     * Creates new form CadastroUsuarios
     */
    public CadastroUsuariosVIEW() {
        initComponents();
        controller = new CadastroUsuarioController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlInformacoesPessoais = new javax.swing.JLabel();
        jlNomeCompleto = new javax.swing.JLabel();
        jtfNomeCompleto = new javax.swing.JTextField();
        jlDtNasc = new javax.swing.JLabel();
        jftfDtNasc = new javax.swing.JFormattedTextField();
        jtfCPF = new javax.swing.JTextField();
        jlCPF = new javax.swing.JLabel();
        jtfRG = new javax.swing.JTextField();
        jtfRG_OrgaoEmissor = new javax.swing.JTextField();
        jlRG_OrgaoEmissor = new javax.swing.JLabel();
        jlRG = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        jftfTelefonePessoal = new javax.swing.JFormattedTextField();
        jlTelefonePessoal = new javax.swing.JLabel();
        jftfTelefoneRecados = new javax.swing.JFormattedTextField();
        jlTelefoneRecados = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jlInstrucao = new javax.swing.JLabel();
        jlPermissoesUsuario = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlCriadoEm = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jtfData = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jcbGestorUsuarios = new javax.swing.JCheckBox();
        jcbGestorQuadras = new javax.swing.JCheckBox();
        jcbZelador = new javax.swing.JCheckBox();
        jcbAnalistaRelatorios = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jbCancelar = new javax.swing.JButton();
        jbRemoverUsuario = new javax.swing.JButton();
        jbAdicionarUsuario = new javax.swing.JButton();
        jbEditarUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de usuários");
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlInformacoesPessoais.setBackground(new java.awt.Color(232, 255, 255));
        jlInformacoesPessoais.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlInformacoesPessoais.setText("Informações pessoais:");
        getContentPane().add(jlInformacoesPessoais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jlNomeCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/Nome.png"))); // NOI18N
        jlNomeCompleto.setText("Nome completo:");
        getContentPane().add(jlNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jtfNomeCompleto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jtfNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 250, -1));

        jlDtNasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/Consultar agenda.png"))); // NOI18N
        jlDtNasc.setText("Data de Nascimento:");
        getContentPane().add(jlDtNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jftfDtNasc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jftfDtNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, -1));
        getContentPane().add(jtfCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 160, -1));

        jlCPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/fingerprint-18p.png"))); // NOI18N
        jlCPF.setText("C.P.F:");
        getContentPane().add(jlCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));
        getContentPane().add(jtfRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 160, -1));
        getContentPane().add(jtfRG_OrgaoEmissor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 120, -1));

        jlRG_OrgaoEmissor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/Publico.png"))); // NOI18N
        jlRG_OrgaoEmissor.setText("Orgão Emissor:");
        getContentPane().add(jlRG_OrgaoEmissor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, -1));

        jlRG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/fingerprint-18p.png"))); // NOI18N
        jlRG.setText("R.G:");
        getContentPane().add(jlRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));
        getContentPane().add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 320, -1));

        jlEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/e-mail (2).png"))); // NOI18N
        jlEmail.setText("E-mail:");
        getContentPane().add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));
        getContentPane().add(jftfTelefonePessoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 140, -1));

        jlTelefonePessoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/Contato pessoal.png"))); // NOI18N
        jlTelefonePessoal.setText("Telefone pessoal:");
        getContentPane().add(jlTelefonePessoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));
        getContentPane().add(jftfTelefoneRecados, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 140, -1));

        jlTelefoneRecados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/Telefone.png"))); // NOI18N
        jlTelefoneRecados.setText("Telefone recados:");
        getContentPane().add(jlTelefoneRecados, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jlTitulo.setText("Controle de usuários");
        getContentPane().add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jlInstrucao.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlInstrucao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jlInstrucaoPropertyChange(evt);
            }
        });
        getContentPane().add(jlInstrucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 790, 20));

        jlPermissoesUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/Permissões.png"))); // NOI18N
        jlPermissoesUsuario.setText("Permissões do usuário: ");
        getContentPane().add(jlPermissoesUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, 30));

        jlID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/ID.png"))); // NOI18N
        jlID.setText("ID:");
        getContentPane().add(jlID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, -1));

        jlSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/Senha.png"))); // NOI18N
        jlSenha.setText("Senha: ");
        getContentPane().add(jlSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 100, -1));

        jlCriadoEm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/data-atual.png"))); // NOI18N
        jlCriadoEm.setText("Criado em:");
        getContentPane().add(jlCriadoEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));

        jtfID.setEditable(false);
        jtfID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jtfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, -1));

        jtfData.setEditable(false);
        jtfData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jtfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 90, -1));

        jpfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jpfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 200, -1));

        jcbGestorUsuarios.setBorder(null);
        getContentPane().add(jcbGestorUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jcbGestorQuadras.setBorder(null);
        getContentPane().add(jcbGestorQuadras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jcbZelador.setBorder(null);
        jcbZelador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbZeladorActionPerformed(evt);
            }
        });
        getContentPane().add(jcbZelador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jcbAnalistaRelatorios.setBorder(null);
        getContentPane().add(jcbAnalistaRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jCheckBox1.setBorder(null);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        jCheckBox2.setBorder(null);
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, -1, -1));

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/Sair.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 110, -1));

        jbRemoverUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/remove-user.png"))); // NOI18N
        jbRemoverUsuario.setText("Remover");
        jbRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jbRemoverUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 110, -1));

        jbAdicionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/Adicionar usuário.png"))); // NOI18N
        jbAdicionarUsuario.setText("Salvar");
        jbAdicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jbAdicionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 100, -1));

        jbEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/edit-user.png"))); // NOI18N
        jbEditarUsuario.setText("Editar");
        getContentPane().add(jbEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/disable-user-18p.png"))); // NOI18N
        jLabel1.setText("Desabilitado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/block-user-18dp.png"))); // NOI18N
        jLabel2.setText("Bloqueado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/icones/Usuário.png"))); // NOI18N
        jLabel3.setText("Usuário único:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, -1));

        jLabel4.setText("Zelador");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 20));

        jLabel5.setText("Analista de relatórios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        jLabel6.setText("Gestor de quadras");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 20));

        jLabel7.setText("Gestor de usuários");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 20));

        jlFundo.setBackground(new java.awt.Color(204, 204, 255));
        jlFundo.setForeground(new java.awt.Color(204, 255, 255));
        jlFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/VIEW/imagens/fundo3.png"))); // NOI18N
        getContentPane().add(jlFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfSenhaActionPerformed

    private void jcbZeladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbZeladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbZeladorActionPerformed

    private void jbRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverUsuarioActionPerformed
        
    }//GEN-LAST:event_jbRemoverUsuarioActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        controller.cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarUsuarioActionPerformed
        controller.salvarUsuario();
    }//GEN-LAST:event_jbAdicionarUsuarioActionPerformed

    private void jlInstrucaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jlInstrucaoPropertyChange
        jlInstrucao.setText("<html><body>*Preencha todos os campos ou edite os campos necessários e aperte o botão correspondente "
                + "para adicionar adicionar, modificar ou remover um usuário.</body></html>");
    }//GEN-LAST:event_jlInstrucaoPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtfData.setText(controller.dataAtual());
    }//GEN-LAST:event_formWindowOpened

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuariosVIEW().setVisible(true);
            }
        });
    }

    public JCheckBox getJcbAnalistaRelatorios() {
        return jcbAnalistaRelatorios;
    }

    public void setJcbAnalistaRelatorios(JCheckBox jcbAnalistaRelatorios) {
        this.jcbAnalistaRelatorios = jcbAnalistaRelatorios;
    }

    public JCheckBox getJcbGestorQuadras() {
        return jcbGestorQuadras;
    }

    public void setJcbGestorQuadras(JCheckBox jcbGestorQuadras) {
        this.jcbGestorQuadras = jcbGestorQuadras;
    }

    public JCheckBox getJcbGestorUsuarios() {
        return jcbGestorUsuarios;
    }

    public void setJcbGestorUsuarios(JCheckBox jcbGestorUsuarios) {
        this.jcbGestorUsuarios = jcbGestorUsuarios;
    }

    public JCheckBox getJcbZelador() {
        return jcbZelador;
    }

    public void setJcbZelador(JCheckBox jcbZelador) {
        this.jcbZelador = jcbZelador;
    }

    public JPasswordField getJpfSenha() {
        return jpfSenha;
    }

    public void setJpfSenha(JPasswordField jpfSenha) {
        this.jpfSenha = jpfSenha;
    }

    public JTextField getJtfEmail() {
        return jtfEmail;
    }

    public void setJtfEmail(JTextField jtfEmail) {
        this.jtfEmail = jtfEmail;
    }

    public JTextField getJtfID() {
        return jtfID;
    }

    public void setJtfID(JTextField jtfID) {
        this.jtfID = jtfID;
    }

    public JTextField getJtfNomeCompleto() {
        return jtfNomeCompleto;
    }

    public void setJtfNomeCompleto(JTextField jtfNomeCompleto) {
        this.jtfNomeCompleto = jtfNomeCompleto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbAdicionarUsuario;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditarUsuario;
    private javax.swing.JButton jbRemoverUsuario;
    private javax.swing.JCheckBox jcbAnalistaRelatorios;
    private javax.swing.JCheckBox jcbGestorQuadras;
    private javax.swing.JCheckBox jcbGestorUsuarios;
    private javax.swing.JCheckBox jcbZelador;
    private javax.swing.JFormattedTextField jftfDtNasc;
    private javax.swing.JFormattedTextField jftfTelefonePessoal;
    private javax.swing.JFormattedTextField jftfTelefoneRecados;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlCriadoEm;
    private javax.swing.JLabel jlDtNasc;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlFundo;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlInformacoesPessoais;
    private javax.swing.JLabel jlInstrucao;
    private javax.swing.JLabel jlNomeCompleto;
    private javax.swing.JLabel jlPermissoesUsuario;
    private javax.swing.JLabel jlRG;
    private javax.swing.JLabel jlRG_OrgaoEmissor;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTelefonePessoal;
    private javax.swing.JLabel jlTelefoneRecados;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfData;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfNomeCompleto;
    private javax.swing.JTextField jtfRG;
    private javax.swing.JTextField jtfRG_OrgaoEmissor;
    // End of variables declaration//GEN-END:variables
}
